import type { Metadata } from "next";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import { IBM_Plex_Sans} from "next/font/google";
import "./globals.css";
import {cn} from "../lib/utils"

const IBMPlex = IBM_Plex_Sans({
  subsets : ['latin'],
  weight: ['400','500','600'],
  variable: '--font-ibm-plex'
});

export const metadata: Metadata = {
  title: "Imagify",
  description: "Generated by Create Image using AI",
};

export default function RootLayout({
  children,
}: Readonly<{  
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          
          <main>{children}</main>
          {/* <header>
            <SignedOut>
              <SignInButton />
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header> */}
        </body>
      </html>
    </ClerkProvider>
  );
}
